class MyException extends Exception{
	private int detail;

	MyException(int a){
		detail=a;
	}

	public String toString(){
		return "MyException [" +detail + " user defined Exception" + "]";
	}

}

class ExceptionDemo{
	static void compute(int a) throws MyException
	{
		System.out.println("Called compute(" + a+") " );
		 
		if(a>10)
		throw new MyException(a);

		System.out.println("Normal exit");
	}

	public static void main(String args[]){
		try{
		compute(1);
		compute(20);
	      }


		catch(MyException e){
		System.out.println("Caught " +e);
		}

		
		try{
		int l = args.length;
		System.out.println("l = "+ l);
		int b=40/l;
		}
	
		catch(ArithmeticException e){

		System.out.println("Divide by 0: "+e);
		}

	}
}
